# Generated by Django 5.2.3 on 2025-07-28 09:30

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                blank=True,
                default="avatars/avatar_default.png",
                null=True,
                upload_to=users.models.user_avatar_upload_path,
                verbose_name="Фотография",
            ),
        ),
    ]
