services:
  news_service:
    container_name: news
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9999:9999"
    volumes:
      - newsstatic_volume:/app/static
      - newsmedia_volume:/app/media
    entrypoint: [ "/app/entrypoint.sh" ]

volumes:
  newsmedia_volume:
  newsstatic_volume:
