"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-zoxz^(^%&(mn73=sn4&h96rnx7#%pty+s3!c%%on9ofw=-s+z6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # библиотеки
    "django_mptt_admin",
    "django_ckeditor_5",
    "reversion",
    "parler",
    # локальные приложения
    "users",
    "app_content",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# LANGUAGE_CODE = "en-us"

# TIME_ZONE = "UTC"

# USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

# STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# ============================== мои настройки ==============================

AUTH_USER_MODEL = "users.User"

USE_I18N = True  # включает механизм переводов
USE_L10N = True  # форматирование дат/чисел

LANGUAGE_CODE = "ru"  # язык по умолчанию
TIME_ZONE = "Asia/Almaty"  # ваш часовой пояс

LANGUAGES = [
    ("ru", "Русский"),
    ("kk", "Қазақша"),
    ("en", "English"),  # опционально оставляем английский как fallback
]

LOCALE_PATHS = [BASE_DIR / "locale"]

from .ckediror_settings import (
    customColorPalette,
    CKEDITOR_5_CONFIGS,
    # CKEDITOR_5_CUSTOM_CSS,
    # CKEDITOR_5_FILE_STORAGE,
)

customColorPalette = customColorPalette
CKEDITOR_5_CONFIGS = CKEDITOR_5_CONFIGS
# CKEDITOR_5_CUSTOM_CSS = CKEDITOR_5_CUSTOM_CSS
# CKEDITOR_5_FILE_STORAGE = CKEDITOR_5_FILE_STORAGE

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

STATIC_URL = "/static/"  # URL, по которому браузер запрашивает файлы
STATIC_ROOT = BASE_DIR / "staticfiles"  # каталог, куда collectstatic их скопирует


PARLER_LANGUAGES = {
    # «None» — глобальный набор языков
    None: (
        {"code": "ru"},
        {"code": "kk"},
        {"code": "en"},
    ),
    "default": {
        "fallback": "ru",  # порядок отката, если нет перевода
        "hide_untranslated": False,  # = показывать obj и без перевода
    },
}


CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

CSRF_TRUSTED_ORIGINS = [
    "http://185.100.67.246:9999",
]
CORS_ALLOWED_ORIGINS = [
    "https://sck.kz",
]
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = "Lax"
