# Generated by Django 5.2.3 on 2025-06-22 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_content", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="app_content.tag",
                verbose_name="теги",
            ),
        ),
    ]
