# Generated by Django 5.2.3 on 2025-07-08 17:53

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_content", "0002_article_tags"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                related_name="articles",
                to="app_content.category",
                verbose_name="рубрики",
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles/covers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    )
                ],
                verbose_name="обложка",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("review", "На модерации"),
                    ("published", "Опубликовано"),
                    ("archived", "В архиве"),
                ],
                default="draft",
                max_length=10,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="categorytranslation",
            name="name",
            field=models.CharField(max_length=120, verbose_name="название"),
        ),
    ]
