# Generated by Django 5.2.3 on 2025-07-08 19:26

import app_content.models.article
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_content", "0003_article_category_article_cover_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                null=True,
                upload_to="articles/covers/thumbnails/",
                verbose_name="миниатюра",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="articles/covers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    app_content.models.article.validate_image_size,
                    app_content.models.article.validate_image_resolution,
                ],
                verbose_name="обложка",
            ),
        ),
    ]
