# Generated by Django 5.2.3 on 2025-07-08 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_content", "0004_article_cover_thumbnail_alter_article_cover_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0, editable=False, verbose_name="кол-во просмотров"
            ),
        ),
    ]
