# Generated by Django 5.2.3 on 2025-07-28 09:30

import app_content.models.article
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_content", "0005_article_views_count"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="author",
            field=models.ForeignKey(
                help_text="Пользователь, создавший статью.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="articles",
                to=settings.AUTH_USER_MODEL,
                verbose_name="автор",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="category",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите одну или несколько рубрик, к которым относится статья.",
                related_name="articles",
                to="app_content.category",
                verbose_name="рубрики",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_image",
            field=models.ImageField(
                blank=True,
                help_text="Макс. размер 2\u202fМБ. Разрешение до 1920x1080px. Допустимые форматы: jpg, jpeg, png, webp.",
                null=True,
                upload_to="articles/covers/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["jpg", "jpeg", "png", "webp"]
                    ),
                    app_content.models.article.validate_image_size,
                    app_content.models.article.validate_image_resolution,
                ],
                verbose_name="обложка",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="cover_thumbnail",
            field=models.ImageField(
                blank=True,
                editable=False,
                help_text="Создаётся автоматически при загрузке обложки.",
                null=True,
                upload_to="articles/covers/thumbnails/",
                verbose_name="миниатюра",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата и время создания записи (устанавливается автоматически).",
                verbose_name="Время создания статьи",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Статья станет видимой как опубликованная только после наступления указанной даты и времени.",
                null=True,
                verbose_name="дата публикации",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("review", "На модерации"),
                    ("published", "Опубликовано"),
                    ("archived", "В архиве"),
                ],
                default="draft",
                help_text="Текущий статус публикации статьи.",
                max_length=10,
                verbose_name="статус",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                help_text="Выберите один или несколько тегов, подходящих к содержанию статьи.",
                related_name="articles",
                to="app_content.tag",
                verbose_name="теги",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True,
                help_text="Дата и время последнего обновления записи.",
                verbose_name="Время последнего изменения статьи",
            ),
        ),
        migrations.AlterField(
            model_name="article",
            name="views_count",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="Количество просмотров статьи (автоматически обновляется).",
                verbose_name="кол-во просмотров",
            ),
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="content",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text="Основной текст статьи с форматированием.",
                verbose_name="контент",
            ),
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="slug",
            field=models.SlugField(
                help_text="Уникальный URL-идентификатор. Только латиница, цифры и дефисы.",
                max_length=250,
                unique=True,
                verbose_name="slug",
            ),
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="summary",
            field=models.TextField(
                blank=True,
                help_text="Краткое описание статьи, используется в предпросмотре.",
                verbose_name="краткое описание",
            ),
        ),
        migrations.AlterField(
            model_name="articletranslation",
            name="title",
            field=models.CharField(
                help_text="Введите заголовок статьи, он будет отображаться на странице.",
                max_length=250,
                verbose_name="заголовок",
            ),
        ),
    ]
