# Generated by Django 5.2.3 on 2025-08-01 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_content", "0006_alter_article_author_alter_article_category_and_more"),
    ]

    operations = [
        # Enable pg_trgm if not exists
        migrations.RunSQL(
            "CREATE EXTENSION IF NOT EXISTS pg_trgm;",
            reverse_sql="""
                -- Обычно не удаляем pg_trgm, чтобы не ломать другие зависимости
            """,
        ),
        # ArticleTranslation full-text and trigram
        migrations.RunSQL(
            """
            CREATE INDEX article_translation_search_idx
            ON app_content_article_translation
            USING GIN (
              to_tsvector('russian', coalesce(title, '') || ' ' || coalesce(summary, '') || ' ' || coalesce(content, ''))
            );
            """,
            reverse_sql="DROP INDEX IF EXISTS article_translation_search_idx;",
        ),
        migrations.RunSQL(
            """
            CREATE INDEX article_translation_title_trgm_idx
            ON app_content_article_translation
            USING GIN (title gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS article_translation_title_trgm_idx;",
        ),
        # TagTranslation full-text and trigram
        migrations.RunSQL(
            """
            CREATE INDEX tag_translation_name_search_idx
            ON app_content_tag_translation
            USING GIN (to_tsvector('russian', name));
            """,
            reverse_sql="DROP INDEX IF EXISTS tag_translation_name_search_idx;",
        ),
        migrations.RunSQL(
            """
            CREATE INDEX tag_translation_name_trgm_idx
            ON app_content_tag_translation
            USING GIN (name gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS tag_translation_name_trgm_idx;",
        ),
        # CategoryTranslation full-text and trigram
        migrations.RunSQL(
            """
            CREATE INDEX category_translation_name_search_idx
            ON app_content_category_translation
            USING GIN (to_tsvector('russian', name));
            """,
            reverse_sql="DROP INDEX IF EXISTS category_translation_name_search_idx;",
        ),
        migrations.RunSQL(
            """
            CREATE INDEX category_translation_name_trgm_idx
            ON app_content_category_translation
            USING GIN (name gin_trgm_ops);
            """,
            reverse_sql="DROP INDEX IF EXISTS category_translation_name_trgm_idx;",
        ),
    ]
